# Generated by Django 2.1.4 on 2019-01-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_ID', models.CharField(max_length=3, unique=True)),
                ('app_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_ID', models.CharField(max_length=3, unique=True)),
                ('region_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='app_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolingstrat.AppType'),
        ),
    ]
